<?php

namespace UnknowL\Player;

use pocketmine\form\Form;
use pocketmine\item\VanillaItems;
use pocketmine\nbt\tag\CompoundTag;
use pocketmine\player\Player;
use UnknowL\Games\GameInterface;
use UnknowL\Groups\TeamManager;
use UnknowL\Rank\PremiumRank;
use UnknowL\Rank\Rank;
use UnknowL\Trait\VectorUtilsTrait;
use UnknowL\Utils\PlayerUtils;
use UnknowL\Utils\Scoreboard;

class PolarisPlayer extends Player{

    use VectorUtilsTrait;

    private TeamManager $teamManager;

    public array $request = [];

    private Rank $rank;

    private Scoreboard $activeScoreboard;

    public GameInterface|null $actualGame = null;

    public bool $isRiding = false, $inGame = false;

    private PlayerProperties $properties;

    /**
     * @var bool[]
     */
    public array $hasAccepted = [];

    public function initEntity(CompoundTag $nbt): void
    {
        $this->player = $this;
        $this->rank = new PremiumRank();
        $this->properties = new PlayerProperties();
        parent::initEntity($nbt);
        $this->setScoreboard(PlayerUtils::getBaseScoreboard($this));
        $this->teamManager = new TeamManager($this);
    }

    public function addResquest(string $name, mixed $value = null): void
    {
        $this->request[$name][] = $value;
    }

    public function isRiding(): bool
    {
        return $this->isRiding;
    }

    public function setRiding(bool $ride): void
    {
        $this->isRiding = $ride;
    }

    public function getScoreboard(): Scoreboard
    {
        return $this->activeScoreboard;
    }

    public function setScoreboard(Scoreboard $scoreboard): void
    {
        $this->activeScoreboard = $scoreboard;
    }


    public function getRequest(string $name): mixed
    {
        return $this->request[$name] ?? null;
    }

    public function isPremium(): bool
    {
        return $this->rank instanceof PremiumRank;
    }



    public function isInGame(): bool
    {
        return $this->inGame;
    }

    public function getActualGame(): ?GameInterface
    {
        return $this->actualGame;
    }


    public function push(): void{
        $vector = $this->getMatchedVector(1, 1);
        $this->getMotion()->add($vector->x, $vector->y, $vector->z);
    }

    public function leaveGame(GameInterface $game): void{

    }

    public function joinGame(GameInterface $game): void{
        $team = $this->teamManager->getTeam();
        if($this->getTeamManager()->hasTeam()){
            foreach ($team->getMembers() as $member){
                if(!$this->inGame){
                    PlayerUtils::sendVerification($member, function (PolarisPlayer $player) use ($member, $game) {
                        $member->sendMessage("§c{$this->getName()} §7à rejoint la partie".$game->getName());
                        $game->join($player);
                    });
                }
            }
        }else{
            $game->join($this);
        }
    }

    public function sendForm(Form $form): void
    {
        if($this->properties->getProperties("cleanScreen") === true){
            $this->properties->setProperties("cleanScreen", false);
            parent::sendForm($form); // TODO: Change the autogenerated stub
        }
    }

    public function canJoin(GameInterface $game): bool{
        return !$game->properties->getProperties("Starting") && !$game->properties->getProperties("Ending") && $this->hasAccepted($game);
    }

    public function hasAccepted(GameInterface $game): bool{
        return $this->hasAccepted[$game->getName()] ?? false;
    }

    public function getTeamManager(): TeamManager{
        return $this->teamManager;
    }

    public function getPlayerProperties(): PlayerProperties{
        return $this->properties;
    }

    public function giveHubStuff(PolarisPlayer $player){
        $player->getInventory()->setItem(0, VanillaItems::COMPASS()->setCustomName("Mode de Jeu"));
    }
}